services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sequ-achievement-api
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DB_HOST: host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4009:4009"
    volumes:
      - ./.env:/app/.env:ro
      - ./uploads:/app/uploads
