// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "openapi": "3.0.3",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@sequspace.com"
        },
        "version": "{{.Version}}"
    },
    "servers": [
        {
            "url": "https://sequachievementapi.sequspace.com/api/v1",
            "description": "production server"
        },
        {
            "url": "http://localhost:{port}/api/v1",
            "variables": {
                "port": {
                    "default": "4006"
                }
            }
        }
    ],
    "paths": {
        "/achievements/shining-star": {
            "get": {
                "description": "Get a list of all shining stars across the system",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "achievements"
                ],
                "summary": "Get all shining stars",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new shining star achievement for a user with a certificate upload",
                "tags": [
                    "achievements"
                ],
                "summary": "Create a new shining star achievement",
                "requestBody": {
                    "required": true,
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "required": ["user_id", "type", "description"],
                                "properties": {
                                    "user_id": {
                                        "type": "integer",
                                        "description": "User ID",
                                        "example": 1
                                    },
                                    "type": {
                                        "type": "string",
                                        "description": "Achievement Type",
                                        "enum": ["Task Master", "Consistency Star", "Speed Performer", "Deadline Champion", "Productivity Pro", "1 trip around"]
                                    },
                                    "description": {
                                        "type": "string",
                                        "description": "Description of the achievement"
                                    },
                                    "certificate": {
                                        "type": "string",
                                        "format": "binary",
                                        "description": "Certificate file to upload"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/achievements/shining-star/{user_id}": {
            "get": {
                "description": "Get a list of shining stars for a specific user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "achievements"
                ],
                "summary": "Get user's shining stars",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4009",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Sequspace Achievements API",
	Description:      "This is the microservice for Sequspace achievements, handling shining stars and other awards.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
